### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by Raunak173** [DecodersCommunity/animepedia#140]
Website has started looking messy, so it would be great if we could implement pagination function, so that a user can navigate between pages and each page can show a max of 10 cards.

**Comment by Rahul-Palahwat** [comment]
Hey @Raunak173 can you assign this issue to me

**Comment by iamartyaa** [comment]
This issue has been assigned to you, can start working on it now!

**Comment by Aviral2002** [comment]
can I work on this?

**Comment by Raunak173** [comment]
Hi @Rahul-Palahwat , I guess this issue is taking longer than expected. Would you still like to work on it or I may proceed with someone else.

**Comment by Rahul-Palahwat** [comment]
Hey @Raunak173 as i have to make it whole in a array...i will be doing this most probably by EOD or by tomorrow morning

**Comment by BarmenduC** [comment]
All good @Rahul-Palahwat , Do mention the issue number on your pull request.

**Comment by AnantJain05** [comment]
Hey @Raunak173 , Can you assign this issue to me? As I have already done this thing before, I can complete it by today or tomorrow morning.

**Comment by BarmenduC** [comment]
@AnantJain05 I am assigning this issue to you.
