### ISSUE TITLE
Minor changes required in the light & dark mode

### ISSUE THREAD

**Issue by iamartyaa** [DecodersCommunity/animepedia#142]
- Change the font color of 'AnimePedia' and 'All Anime Characters' in both the dark & light modes.
- In the dark mode, Change the colors of the Card content & the card color itself to make it look cooler :)

**Comment by Rahul-Palahwat** [comment]
Hey @iamartyaa please assign this issue to me

**Comment by SumeetHaryani** [comment]
@iamartyaa I would like to work on this issue

**Comment by iamartyaa** [comment]
I am assigning this issue to @Rahul-Palahwat , you can start working on it.
@SumeetHaryani I will be opening a few more issues within the next 1 hour and will assign them to you.

**Comment by AadishJain249** [comment]
@iamartyaa  can i work on this issue

**Comment by iamartyaa** [comment]
> @iamartyaa can i work on this issue

This issue is already assigned.
