### ISSUE TITLE
Searchbar border update

### ISSUE THREAD

**Issue by iamartyaa** [DecodersCommunity/animepedia#145]
- Search bar background/border is not visible in the light mode. Also, change the color of the search icon to black. 

![Screenshot 2022-10-02 124034](https://user-images.githubusercontent.com/74955989/193442560-bc2de1a6-3e2e-4076-9c37-7b6d5002c1b7.png)

**Comment by iamartyaa** [comment]
@SumeetHaryani would you like to take up this issue ?

**Comment by Akshay9607** [comment]
hello i would like to work on this issue

**Comment by SumeetHaryani** [comment]
Yes, you can assign it to me :)

**Comment by iamartyaa** [comment]
Assigned. Make sure to mention the issue no in your PR's description.

**Comment by SumeetHaryani** [comment]
sure
