### ISSUE TITLE
Add move to bottom button

### ISSUE THREAD

**Issue by BarmenduC** [DecodersCommunity/animepedia#173]
Add a button (Taking reference from the move to top button) to move to the bottom of the page.

**Comment by astroidworld** [comment]
can you assign it to me

**Comment by BarmenduC** [comment]
Sure Astroidworld

**Comment by RahulRudra81** [comment]
can i work on this too

**Comment by BarmenduC** [comment]
Since this issue has already been assigned to someone, could you try to work on one of the other present issues on the website. You could also just browse the website and raise an issue yourself.

**Comment by AnantJain05** [comment]
Hey @BarmenduC , I can work on this issue. I will complete it by today EOD. Can you please assign this to me?

**Comment by Raunak173** [comment]
Hi, I'm assigningthis to you anant
