### ISSUE TITLE
add naruto anime loader add loader

### ISSUE THREAD

**Issue by shreyashkr17** [DecodersCommunity/animepedia#184]

**Comment by iamartyaa** [comment]
Can you please provide a description of what you want to add?

**Comment by shreyashkr17** [comment]
I want to add a loader of naruto animation... Which will run for example 5 sec.. then it will automatically turn to ur main page.. Which can improve the front end of ur page.?

**Comment by iamartyaa** [comment]
Okay sounds cool ! I am adding the Hacktoberfest label and you can start working on it. Make sure to mention the issue no. In the description of your Pull Request. Thank you for choosing AnimePedia.

**Comment by Samar1110** [comment]
@iamartyaa, @Raunak173  can i work on this issue, add a cool naruto spinner/loader.

**Comment by shreyashkr17** [comment]
this is already done and merged.
