### ISSUE TITLE
Input class and my search class overlapping together, due to which input search bar appears first on clicking icon, 

### ISSUE THREAD

**Issue by rohitmultani** [DecodersCommunity/animepedia#285]
![image](https://user-images.githubusercontent.com/85426206/193771567-1ef969ba-32df-4c37-82fa-e8544e173002.png)

**Comment by iamartyaa** [comment]
This issue has been assigned to you @DYNAMICMORTAL .  Make sure you mention the issue number in the description of your PR.

**Comment by yogesh-9999** [comment]
Hey @rohitmultani  assign this issue to me
