### ISSUE TITLE
Add a new Anime Character

### ISSUE THREAD

**Issue by DYNAMICMORTAL** [DecodersCommunity/animepedia#316]
Please assign me this task. Thank you in advance.

**Comment by jackson-roberio** [comment]
> Please assign me this task @jackson-roberio . Thank you in advance.

I can't sign, I believe only the repository owner.

**Comment by DYNAMICMORTAL** [comment]
@jackson-roberio please tag the repo owner,as I don't know his id. Thank yoi

**Comment by iamartyaa** [comment]
You don't need to open an issue to add a new character @DYNAMICMORTAL . You can simply add the character , open PR and mention the issue no #4 . Thank you
