### ISSUE TITLE
Optimize search engine

### ISSUE THREAD

**Issue by lutfiandri** [DecodersCommunity/animepedia#337]
- search not only by full string, but each word
- show not found error if not found instead of show nothing

**Comment by Raunak173** [comment]
It looks like a good suggestion to me. Ok I'm assigning you this task. Please also mention the Issue number in your PR.

**Comment by lutfiandri** [comment]
okey..

**Comment by Raunak173** [comment]
@lutfiandri What's the progress?

**Comment by Raunak173** [comment]
Yes sure @stenwire , I'm assigning this to you.
