### ISSUE TITLE
Change layout of Anime Characters

### ISSUE THREAD

**Issue by iamartyaa** [DecodersCommunity/animepedia#34]
It would be better if there were 2 anime character cards in one line/row.

**Comment by SanjaySargam** [comment]
Can u plz assign me ?

**Comment by Accelerator321** [comment]
sir can u assign it me?

**Comment by iamartyaa** [comment]
Okay, I am assigning it to you @Accelerator321 . Just make sure when you open a pull request, do mention issue no.
