### ISSUE TITLE
Fix the search bar

### ISSUE THREAD

**Issue by iamartyaa** [DecodersCommunity/animepedia#35]
The search bar is not collapsing. 
After opening the Search bar when we click the 'x' icon, the search bar should collapse, but it is not.

**Comment by SanjaySargam** [comment]
Can u plz assign me?

**Comment by iamartyaa** [comment]
Yes, sure! I am assigning it to you.

**Comment by SanjaySargam** [comment]
> Yes, sure! I am assigning it to you.


> Yes, sure! I am assigning it to you. Make sure you mention the issue number when you Open the Pull Request

ok thank you

**Comment by Kushagra-1404** [comment]
Sir can you pls assign me ?
I have solved this issue.

**Comment by iamartyaa** [comment]
This issue has been solved! Thank you for your contributions !
