### ISSUE TITLE
i would like to implement footer and better navbar 

### ISSUE THREAD

**Issue by shivamsisodia07** [DecodersCommunity/animepedia#413]
@iamartyaa @Raunak173 I would like to implement a more attractive navbar and footer for the website, for Hactoberfest-2022

**Comment by Raunak173** [comment]
Yeah sure. Please go ahead

**Comment by OneAutumLeaf** [comment]
@iamartyaa @Raunak173 I would like to add a moreappealing navbar and footer for the website, for Hactoberfest-2022

**Comment by shivamsisodia07** [comment]
@Raunak173 I have completed the task
