### ISSUE TITLE
Change font of mobile version to same as desktop version

### ISSUE THREAD

**Issue by iamartyaa** [DecodersCommunity/animepedia#440]
Change the font style of mobile version, make it same as the desktop site. Also change the font color of "AnimePedia" to dark grey or black and "All Anime Characters" to something familiar.

**Comment by Chaitanya-087** [comment]
i would like to work on this

**Comment by iamartyaa** [comment]
Ok I will be assigning you the issue. Kindly mention the issue no. in the description of your PR

**Comment by FixxooXD** [comment]
@iamartyaa bro iam also working in this issue already

**Comment by iamartyaa** [comment]
Is it so @FixxooXD ? I didn't see any open issue regarding it. Anyways you can continue working ok it and open a PR.

**Comment by FixxooXD** [comment]
@iamartyaa I cant see any change in the font style in mobile version i had changed the colour of "ANIMEPEDIA" can i put a pr 
?

**Comment by Sandydwivedi** [comment]
I would like to work on this issue.
