### ISSUE TITLE
Fix SearchBar

### ISSUE THREAD

**Issue by iamartyaa** [DecodersCommunity/animepedia#441]
The suggestions in the search bar are overlapped by the carousel below it. Need to add extra padding if suggestions are available.

**Comment by gaut2003** [comment]
assign this to me.

**Comment by iamartyaa** [comment]
I am assigning it to @gautmikhanna . Kindly mention the issue no. In the description of your PR. Thank you

**Comment by iamartyaa** [comment]
@gaut2003 keep an eye on the repository, We will be adding up new issues soon! Thank you.

**Comment by gaut2003** [comment]
I have solved the issue.

**Comment by gaut2003** [comment]
Have sent you a PR fixing this bug. @iamartyaa
