### ISSUE TITLE
Improving UI/UX of Footer & Adding Icon of Github site in the footer

### ISSUE THREAD

**Issue by Samar1110** [DecodersCommunity/animepedia#456]
@iamartyaa @Raunak173  can I improve the UI/UX design of footer and Add Icon of GIthub, Linkedin profile, etc 
For Hactoberfest-2022

**Comment by iamartyaa** [comment]
Yup sure. You can work on the footer design & add icon of GitHub that will redirect to this repo.

**Comment by FixxooXD** [comment]
Ok iam start working in this issue.
