### ISSUE TITLE
Dark mode not working

### ISSUE THREAD

**Issue by rajgautam-cloud** [DecodersCommunity/animepedia#5]
Currently, the feature of the dark mode is not working. Implement that feature

**Comment by Souvik-Nayak** [comment]
Hey, can i work on this issue to implement the dark mode and also try to have a moon & sun button inrespective of a button !

**Comment by sahilrajput18** [comment]
hey can you assign me this issue please?

**Comment by iamartyaa** [comment]
Yes you can take up this issue @Souvik-Nayak .
