### ISSUE TITLE
Site Not Functional as there is no scroll bar

### ISSUE THREAD

**Issue by isyneha** [DecodersCommunity/animepedia#501]
![image](https://user-images.githubusercontent.com/79058289/194738327-d21a8475-8033-4e9a-a029-ce351affeadc.png)

Someone did some changes to the base template due to which there is no scrolling option available.

**Comment by smitioswal** [comment]
Please assign me

**Comment by isyneha** [comment]
@Raunak173 please assign it to @smitioswal

**Comment by Raunak173** [comment]
Ok @smitioswal , I'm assigning this issue to you.

**Comment by Samar1110** [comment]
@isyneha i already know the solution of the above issue ,i also raised the same issue in #497 could you please assign this issue to me for Hactoberfest-2022

**Comment by isyneha** [comment]
@Raunak173 Can we assign it to @Samar1110 as well?

**Comment by smitioswal** [comment]
I have fixed it and created a pr, please check @isyneha @Raunak173

**Comment by smitioswal** [comment]
#502
