### ISSUE TITLE
New Anime

### ISSUE THREAD

**Issue by amanraj-iit** [DecodersCommunity/animepedia#537]

**Comment by amanraj-iit** [comment]
Added new Anime

**Comment by amanraj-iit** [comment]
@Raunak173 sir  please attach label as hackoctober accepted

**Comment by amanraj-iit** [comment]
pull request:  https://github.com/DecodersCommunity/animepedia/pull/536

**Comment by piyush-mahajan** [comment]
can you please assign me this issue? I would love to work on this project.
