### ISSUE TITLE
Remove extra space below footed

### ISSUE THREAD

**Issue by sakshi2407** [DecodersCommunity/animepedia#608]
I want to remove the extra space below the footer
![Screenshot (28)](https://user-images.githubusercontent.com/99481336/195434184-aa9b0cfc-3fdc-4318-938d-264d50c5ea70.png)

**Comment by iamartyaa** [comment]
Okay , assigned to you.

**Comment by dishantzaveri** [comment]
hey, 
 I want to contribute to this repo, could you assign it to me?

**Comment by sakshi2407** [comment]
@iamartyaa The issue of removing extra space below footer was already solved by someone else. So, I'll contribute to the website by adding animation to the main heading AnimePedia

**Comment by sakshi2407** [comment]
https://user-images.githubusercontent.com/99481336/195975583-3597a0e0-e480-4cea-ac0a-4b9fbd94b765.mp4

**Comment by iamartyaa** [comment]
Looks cool to me. Go ahead and create a PR @sakshi2407 !
