### ISSUE TITLE
Anime character's Card bug on Website

### ISSUE THREAD

**Issue by Sanchitbajaj02** [DecodersCommunity/animepedia#613]
Hello, while scrolling through different pages, I found a bug that someone pasted the card inside another card so the page is looking like this 
![image](https://user-images.githubusercontent.com/55249639/195503373-bd337f6f-7965-4872-ba51-c4db06951fdd.png)

![image](https://user-images.githubusercontent.com/55249639/195503424-66b14bd3-562c-4619-a6a3-ac9cad157a3b.png)

Please assign me the issue to fix this bug or any potential bug and it would be better to make this PR Hacktobefest accepted

**Comment by Raunak173** [comment]
Ok, I'm assigning you this issue.

**Comment by Sanchitbajaj02** [comment]
Issue Resolved. Please refer PR #639

**Comment by kunalthedev** [comment]
> Issue Resolved. Please refer PR #639 before having any merge conflct

@Raunak173 Now everything related to UI is looking fine 
Please accept this PR #639
