### ISSUE TITLE
No fixed navbar?

### ISSUE THREAD

**Issue by MadhanDevlpr** [DecodersCommunity/animepedia#652]
a fixed navbar would let users change their theme even when they are exploring animepedia

**Comment by sohamtembhurne** [comment]
Can I be assigned with this issue ?

**Comment by Yvg2244** [comment]
please assign it to me

**Comment by iamartyaa** [comment]
Sounds cool! Sorry for the delay in responding to your issue. Would you still like to work on it?

**Comment by Yvg2244** [comment]
Yes

**Comment by sohamtembhurne** [comment]
Yeah. You can assign the issue to me
