### ISSUE TITLE
Improve the design of the card

### ISSUE THREAD

**Issue by evilseye** [DecodersCommunity/animepedia#8]
- improve the hover function

**Comment by flow6979** [comment]
hey @evilseye, I want to contribute to this repository. can you please assign this to me?

**Comment by iamartyaa** [comment]
Yeap sure. I am assigning you this issue.

**Comment by kaustubhdidit** [comment]
Hey @iamartyaa, Can I work on this too?

**Comment by iamartyaa** [comment]
Sorry @kaustubhdidit , I have already assigned it to @flow6979 . You can take up other open issues or can even suggest one if you want to add/improve/fix anything on the website.
