### ISSUE TITLE
Mobile version fixes

### ISSUE THREAD

**Issue by khushi-purwar** [DecodersCommunity/animepedia#99]
Can I create a search bar in the project @iamartyaa

**Comment by iamartyaa** [comment]
I guess there's a search bar already in the project. Anyway, of you want to improve it somehow then you're welcome.

**Comment by khushi-purwar** [comment]
> I guess there's a search bar already in the project. Anyway, of you want to improve it somehow then you're welcome.

I think it is not visible in mobile view. So i want to work on this issue

**Comment by iamartyaa** [comment]
Okay! Actually, the mobile version is quite poor in UI. Can you please improve the UI by adding proper fonts, font size, and colors? In short, I would like you to improve the UI of the mobile version.

**Comment by iamartyaa** [comment]
Any update @khushi-purwar ?

**Comment by iamartyaa** [comment]
Hey I have merged the enhancement you added. There's an issue though. The search bar is not working ok mobile version now.  Can you fix that up ?

**Comment by Samar1110** [comment]
@iamartyaa can I improve the UI and UX for Mobile version of this site, also can i try to fix the Menu function of this site

**Comment by Samar1110** [comment]
@iamartyaa Can i also add search feature in mobile Version, as the search function is not showing when the screen size is of mobile size

**Comment by iamartyaa** [comment]
Yeap. You can go ahead with your idea of UI in the mobile version @Samar1110 . I am assigning this issue to you.

**Comment by iamartyaa** [comment]
Damnn.. the mobile version looks coool now 🔥✨ Thank you for your contribution @Samar1110
